mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # echo back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /echo
    topic_to: echo
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: echo
    topic_to: /back
  # private path
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /private/echo
    topic_to: ~/echo
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: ~/echo
    topic_to: /private/back
    # boxid/server2box/command to mqtt_bridge/cmd
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: server_bridge.msg:cmd
    topic_from: box_ID/server2box/command
    topic_to: /mqtt_bridge/cmd
 # mqtt_bridge/cmd_ack to boxid/box2server/command_ack PHAN HOI NHAN TRANG THAI
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: server_bridge.msg:cmd_ack
    topic_from: /mqtt_bridge/cmd_ack
    topic_to: box_ID/box2server/command_ack
     # mqtt_bridge/box_info to boxid/box2server/box_info THONG TIN VI TRI
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: server_bridge.msg:box_info
    topic_from: /mqtt_bridge/box_info
    topic_to: boxid/box2server/box_info
     # mqtt_bridge/box_status to boxid/box2server/box_status THONG TIN PIN VA TRANG THAI
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: server_bridge.msg:box_status
    topic_from: /mqtt_bridge/box_status
    topic_to: boxid/box2server/box_status
     # mqtt_bridge/box_weather to boxid/box2server/box_status THONG TIN MOI TRUONG THOI TIET
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: server_bridge.msg:weather
    topic_from: /mqtt_bridge/box_weather
    topic_to: boxid/box2server/box_weather